export const uploadFaceImages = async (req, res) => { return res.json({ ok: true }); };
export const saveFaceDescriptors = async (req, res) => { return res.json({ ok: true }); };
export const getFaceStatus = async (req, res) => { return res.json({ ok: true }); };
export const deleteFaceData = async (req, res) => { return res.json({ ok: true }); };
export const getSessionFaceDescriptors = async (req, res) => { return res.json({ ok: true }); };
export const markFaceAttendance = async (req, res) => { return res.json({ ok: true }); };
export const getFaceStats = async (req, res) => { return res.json({ ok: true }); };
export const getStudentsWithFaceData = async (req, res) => { return res.json({ ok: true }); };
export const getFaceAttendanceLogs = async (req, res) => { return res.json({ ok: true }); };
